"""
Sistema de sincronización SQLite <-> InsForge

Sincroniza automáticamente los cambios en la base de datos local con InsForge Cloud.
"""

import json
import os
import sys
import logging
from datetime import datetime
from typing import Optional
import sqlite3
import requests

# Configuración
INSFORGE_API_KEY = os.getenv('INSFORGE_API_KEY', 'ik_6e043a410661a9bfaed032bf81e065fd')
INSFORGE_API_URL = os.getenv('INSFORGE_API_URL', 'https://vivnx98a.us-east.insforge.app')
INSFORGE_IMPORT_ENDPOINT = f"{INSFORGE_API_URL}/api/database/advance/import"

DB_PATH = os.path.join(os.path.dirname(__file__), '../../..', 'backend', 'larranaga.db')

# Configurar logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(os.path.dirname(__file__), '../../logs/insforge_sync.log')),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# Columnas booleanas que necesitan conversión
BOOLEAN_COLUMNS = {
    "users": ["is_active"],
    "clients": ["is_active"],
    "iva_records": ["filed"],
    "ingresos_brutos": ["filed"],
}

# Columnas binarias a excluir
BINARY_COLUMNS = {
    "limpiezas_iva": ["archivo_corregido"],
}


def export_database_to_sql(db_path: str) -> str:
    """Exporta la base de datos SQLite a SQL compatible con PostgreSQL/InsForge."""

    logger.info(f"Exportando base de datos desde {db_path}")

    try:
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Obtener todas las tablas
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = [row[0] for row in cursor.fetchall()]

        database_dump = {}
        for table in tables:
            cursor.execute(f"SELECT * FROM {table}")
            columns = [description[0] for description in cursor.description]
            rows = cursor.fetchall()

            table_data = []
            for row in rows:
                row_dict = dict(zip(columns, row))
                table_data.append(row_dict)

            database_dump[table] = table_data
            logger.info(f"  Tabla {table}: {len(table_data)} registros")

        conn.close()

        # Generar SQL
        sql_output = generate_sql_from_dump(database_dump)
        logger.info(f"SQL generado: {len(sql_output)} bytes")

        return sql_output

    except Exception as e:
        logger.error(f"Error exportando base de datos: {e}")
        raise


def generate_sql_from_dump(database_dump: dict) -> str:
    """Genera SQL compatible con PostgreSQL a partir del dump JSON."""

    sql_output = """-- Larranaga Database Sync Export
-- Auto-generated by InsForge Sync
-- Generated: {}

BEGIN TRANSACTION;
SET CONSTRAINTS ALL DEFERRED;

""".format(datetime.now().isoformat())

    # CREATE TABLE statements (simplificados)
    create_statements = {
        "users": "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(100), password_hash VARCHAR(255), role VARCHAR(12), is_active BOOLEAN, avatar_initials VARCHAR(3), created_at TIMESTAMP);",
        "clients": "CREATE TABLE IF NOT EXISTS clients (id SERIAL PRIMARY KEY, name VARCHAR(150), business_name VARCHAR(200), cuit VARCHAR(13), clave_fiscal_encrypted TEXT, address VARCHAR(255), phone VARCHAR(30), email VARCHAR(100), category VARCHAR(50), fiscal_condition VARCHAR(50), activity_code VARCHAR(20), is_active BOOLEAN, notes TEXT, created_at TIMESTAMP);",
        "client_collaborators": "CREATE TABLE IF NOT EXISTS client_collaborators (id SERIAL PRIMARY KEY, client_id INTEGER, collaborator_id INTEGER, assigned_at TIMESTAMP, assigned_by_id INTEGER);",
        "tasks": "CREATE TABLE IF NOT EXISTS tasks (id SERIAL PRIMARY KEY, title VARCHAR(200), description TEXT, task_type VARCHAR(22), status VARCHAR(10), client_id INTEGER, collaborator_id INTEGER, period VARCHAR(7), due_date DATE, completed_at TIMESTAMP, blocker_comment TEXT, created_at TIMESTAMP, updated_at TIMESTAMP);",
        "iva_records": "CREATE TABLE IF NOT EXISTS iva_records (id SERIAL PRIMARY KEY, client_id INTEGER, period VARCHAR(7), ventas_gravadas FLOAT, ventas_exentas FLOAT, ventas_no_gravadas FLOAT, debito_fiscal FLOAT, compras_gravadas FLOAT, compras_exentas FLOAT, compras_no_gravadas FLOAT, credito_fiscal FLOAT, saldo_a_favor_anterior FLOAT, saldo FLOAT, filed BOOLEAN, filed_at TIMESTAMP, due_date DATE, vep_number VARCHAR(20), created_at TIMESTAMP);",
        "invoices": "CREATE TABLE IF NOT EXISTS invoices (id SERIAL PRIMARY KEY, client_id INTEGER, collaborator_id INTEGER, invoice_type VARCHAR(1), punto_venta INTEGER, number INTEGER, date DATE, receptor_cuit VARCHAR(13), receptor_name VARCHAR(200), concept VARCHAR(50), neto_gravado FLOAT, neto_no_gravado FLOAT, exento FLOAT, iva_21 FLOAT, iva_105 FLOAT, total FLOAT, cae VARCHAR(14), cae_vto DATE, status VARCHAR(20), created_at TIMESTAMP);",
        "ingresos_brutos": "CREATE TABLE IF NOT EXISTS ingresos_brutos (id SERIAL PRIMARY KEY, client_id INTEGER, period VARCHAR(7), jurisdiction VARCHAR(50), regime VARCHAR(30), base_imponible FLOAT, alicuota FLOAT, impuesto FLOAT, retenciones FLOAT, percepciones FLOAT, saldo FLOAT, filed BOOLEAN, filed_at TIMESTAMP, created_at TIMESTAMP);",
        "subtasks": "CREATE TABLE IF NOT EXISTS subtasks (id SERIAL PRIMARY KEY, task_id INTEGER, title VARCHAR(200), status VARCHAR(10), comment TEXT, created_at TIMESTAMP, updated_at TIMESTAMP);",
        "action_logs": "CREATE TABLE IF NOT EXISTS action_logs (id SERIAL PRIMARY KEY, user_id INTEGER, client_id INTEGER, task_id INTEGER, action_type VARCHAR(50), description TEXT, created_at TIMESTAMP);",
        "comprobantes_recibidos": "CREATE TABLE IF NOT EXISTS comprobantes_recibidos (id SERIAL PRIMARY KEY, client_id INTEGER, period VARCHAR(7), fecha_emision DATE, tipo_comprobante VARCHAR(5), punto_venta VARCHAR(5), numero_desde VARCHAR(20), numero_hasta VARCHAR(20), cod_autorizacion VARCHAR(20), tipo_doc_emisor VARCHAR(5), nro_doc_emisor VARCHAR(13), denominacion_emisor VARCHAR(200), tipo_doc_receptor VARCHAR(5), nro_doc_receptor VARCHAR(13), moneda VARCHAR(5), tipo_cambio FLOAT, imp_neto_gravado FLOAT, imp_neto_no_gravado FLOAT, imp_op_exentas FLOAT, otros_tributos FLOAT, iva FLOAT, imp_total FLOAT, sdk_job_id VARCHAR(64), synced_at TIMESTAMP);",
        "retenciones_percepciones": "CREATE TABLE IF NOT EXISTS retenciones_percepciones (id SERIAL PRIMARY KEY, client_id INTEGER, period VARCHAR(7), cuit_agente VARCHAR(13), impuesto_retenido INTEGER, codigo_regimen INTEGER, tipo_operacion VARCHAR(20), fecha_retencion DATE, fecha_comprobante DATE, importe FLOAT, numero_certificado VARCHAR(50), numero_comprobante VARCHAR(50), descripcion_comprobante VARCHAR(100), codigo_holistor VARCHAR(10), sdk_job_id VARCHAR(64), synced_at TIMESTAMP, comprobante_id INTEGER);",
        "limpiezas_iva": "CREATE TABLE IF NOT EXISTS limpiezas_iva (id SERIAL PRIMARY KEY, client_id INTEGER, user_id INTEGER, nombre_original VARCHAR(255), nombre_corregido VARCHAR(255), total_filas INTEGER, filas_bc_corregidas INTEGER, created_at TIMESTAMP);",
        "movimientos_cc": "CREATE TABLE IF NOT EXISTS movimientos_cc (id SERIAL PRIMARY KEY, client_id INTEGER, tipo VARCHAR(20), monto FLOAT, concepto VARCHAR(255), fecha DATE, notas TEXT, created_at TIMESTAMP);"
    }

    for table_name, create_sql in create_statements.items():
        sql_output += create_sql + "\n"

    sql_output += "\n"

    # Agregar INSERT statements
    total_rows = 0
    for table, rows in database_dump.items():
        for row in rows:
            # Filtrar columnas binarias
            filtered_row = {k: v for k, v in row.items() if k not in BINARY_COLUMNS.get(table, [])}

            cols = ", ".join(f'"{k}"' for k in filtered_row.keys())
            vals = []

            for col_name, v in filtered_row.items():
                if v is None:
                    vals.append("NULL")
                elif col_name in BOOLEAN_COLUMNS.get(table, []):
                    vals.append("true" if v else "false")
                elif isinstance(v, bool):
                    vals.append("true" if v else "false")
                elif isinstance(v, (int, float)):
                    vals.append(str(v))
                else:
                    esc = str(v).replace("'", "''")
                    vals.append(f"'{esc}'")

            vals_str = ", ".join(vals)
            sql_output += f"INSERT INTO {table} ({cols}) VALUES ({vals_str});\n"
            total_rows += 1

    sql_output += f"\nCOMMIT;\n-- Total rows: {total_rows}\n"

    return sql_output


def sync_to_insforge(sql_content: str, retry_attempts: int = 3) -> bool:
    """Sincroniza el SQL a InsForge con reintentos."""

    logger.info(f"Iniciando sincronización a InsForge ({INSFORGE_API_URL})")

    headers = {
        "Authorization": f"Bearer {INSFORGE_API_KEY}"
    }

    for attempt in range(1, retry_attempts + 1):
        try:
            # Guardar SQL en archivo temporal
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', suffix='.sql', delete=False) as f:
                f.write(sql_content)
                temp_file = f.name

            # Upload
            with open(temp_file, 'rb') as f:
                files = {"file": ("larranaga_sync.sql", f)}
                data = {"truncate": "false"}

                logger.info(f"Intento {attempt}/{retry_attempts}: POST {INSFORGE_IMPORT_ENDPOINT}")
                response = requests.post(
                    INSFORGE_IMPORT_ENDPOINT,
                    headers=headers,
                    files=files,
                    data=data,
                    timeout=120
                )

            # Limpiar
            os.unlink(temp_file)

            if response.status_code < 400:
                result = response.json()
                logger.info(f"Sincronización exitosa!")
                logger.info(f"  Tablas: {result.get('tables')}")
                logger.info(f"  Registros: {result.get('rowsImported')}")
                return True
            else:
                logger.warning(f"Intento {attempt} falló: {response.status_code} - {response.text[:200]}")
                if attempt < retry_attempts:
                    import time
                    time.sleep(2 ** attempt)  # Backoff exponencial

        except Exception as e:
            logger.error(f"Intento {attempt} error: {e}")
            if attempt < retry_attempts:
                import time
                time.sleep(2 ** attempt)

    logger.error(f"Sincronización falló después de {retry_attempts} intentos")
    return False


def main():
    """Punto de entrada principal."""

    logger.info("=" * 60)
    logger.info("INICIO: Sincronización SQLite -> InsForge")
    logger.info("=" * 60)

    try:
        # Exportar
        sql_content = export_database_to_sql(DB_PATH)

        # Sincronizar
        success = sync_to_insforge(sql_content)

        if success:
            logger.info("Sincronización completada exitosamente")
            return 0
        else:
            logger.error("Sincronización falló")
            return 1

    except Exception as e:
        logger.error(f"Error fatal: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
